version:  '3.8'

services :
    install-api-arbitrage:
        image:  node:14.15.4
        volumes:
           -  ./api-filter-symbols:/usr/src/app
        working_dir:  /usr/src/app
        command:  npm  i

    install-front-arbitrage:
        build:
           context: ./front-admin-pannel
           dockerfile: dev.Dockerfile
        image: angular:11.0.5
        volumes:
           -  ./front-admin-pannel:/usr/src/app
        working_dir: /usr/src/app
        command:  npm  i

volumes:
      db_arbitrage:
          external: true
