version : '3.8'

services:
   api-arbitrage:
      build:
         context: https://github.com/enzocorp/api-filter-symbols.git
         dockerfile: test.Dockerfile
      container_name : test-api-arbitrage

   front-arbitrage:
      build:
         context: https://github.com/enzocorp/front-admin-pannel.git
         dockerfile: test.Dockerfile
      container_name: test-site-arbitrage
      
   mongo-arbitrage:    
      volumes: 
         - db_test_arbitrage:/data/db

volumes: 
    db_test_arbitrage:
